#
# Copyright (c) Microsoft Corporation
# Licensed under the MIT License.
#

name: tfsec 

on:
  push:
      branches:
      - vnext
      - master

jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Terraform security scan
        uses: triat/terraform-security-scan@v1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}